
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  paramStaticWebsiteHostingBucketName:
    Description: Specify a unique name for S3 bucket that will host static website
    Type: String
    Default: westworld-website-hosting-bucket
    AllowedPattern: "(?!(^xn--|.+-s3alias$))^[a-z0-9][a-z0-9-]{1,61}[a-z0-9]$"  # includes using S3 Transfer Acceleration
    ConstraintDescription: Bucket names must be between 3 (min) and 63 (max) characters long, can consist only of lowercase letters, numbers, dots, and hyphens, must begin and end with a letter or number, etc.
  paramUniqueTagName:
    Description: Specify a unique name for tag
    Type: String
    Default: static-website-hosting-to-s3
    AllowedPattern: "[\\x20-\\x7E]*"
    ConstraintDescription: Must contain only ASCII characters has context menu

Resources:
  myStaticWebsiteHostingBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: your-bucket-name
      DeletionPolicy: Delete
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
        VersioningConfiguration:
          Status: Enabled
        OwnershipControls:
        Rules:
          - ObjectOwnership: ObjectWriter
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
        Tags: 'Cloufrormation'
        Value: 
          ! Ref: ParamUniqueTechName
  myStaticWebsiteHostingBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: 
       ! Ref: myStaticWebsiteHostingBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource:!Join: 
               - ''
               - - 'arn:aws:s3:::'
                 - ! Ref: myStaticWebsiteHostingBucket
                 - /*     

    myStaticWebsiteHostingBucket:
     Type: 'AWS::S3::Bucket'
  
     Properties:
      VersioningConfiguration:
        Status: Enabled

    Outputs:
  outputWebsiteURL:
    Value: 
     ! GetAtt: 
      - myStaticWebsiteHostingBucket
      - WebsiteURL
    Description: Static website URL                 